include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
    
  errors:
    invalid_annotation_target: ignore # Required for Freezed

  exclude:
    - lib/**/*.g.dart

linter:
  rules:
    public_member_api_docs: false
    sort_constructors_first: true
    prefer_const_constructors: true
    prefer_final_locals: true
    require_trailing_commas: true